## Упражнения по библиотеке Numpy

In [365]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [366]:
ar = np.random.randint(-10, 10, size=(1,20))
print(ar)
new_arr = np.where((ar>3)&(ar<8), -ar, ar)
print(new_arr)

[[ -9   7  -8 -10  -4  -9  -8   0  -9   0  -1  -9   3   4  -2  -1  -2   2
    9 -10]]
[[ -9  -7  -8 -10  -4  -9  -8   0  -9   0  -1  -9   3  -4  -2  -1  -2   2
    9 -10]]


**2.** Заменить максимальный элемент случайного массива на 0

In [367]:
ar = np.random.randint(-10, 10, size=(1,20))
print(ar)
max = np.max(ar)
print("Max element:",max)
ar = np.where(ar == max, 0, ar)
print(ar)

[[ -7  -8  -6  -5  -6   3  -9   3  -6  -2   9  -3   8  -8   6   5 -10   0
    9  -8]]
Max element: 9
[[ -7  -8  -6  -5  -6   3  -9   3  -6  -2   0  -3   8  -8   6   5 -10   0
    0  -8]]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [368]:
a = np.random.randint(-10, 10, size=(3, 3))
print(a)
b = np.random.randint(-10, 10, size=(3, 3))
print(b)
multiple = np.outer(a, b)
print(multiple)

[[  4 -10  -8]
 [ -8   2   5]
 [ -3  -3  -2]]
[[  7  -6   4]
 [ -7   5  -8]
 [ -5   3 -10]]
[[ 28 -24  16 -28  20 -32 -20  12 -40]
 [-70  60 -40  70 -50  80  50 -30 100]
 [-56  48 -32  56 -40  64  40 -24  80]
 [-56  48 -32  56 -40  64  40 -24  80]
 [ 14 -12   8 -14  10 -16 -10   6 -20]
 [ 35 -30  20 -35  25 -40 -25  15 -50]
 [-21  18 -12  21 -15  24  15  -9  30]
 [-21  18 -12  21 -15  24  15  -9  30]
 [-14  12  -8  14 -10  16  10  -6  20]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [369]:
A = np.random.randint(-10, 10, size=(8,3))
B = np.random.randint(-10, 10, size=(2,2))
# A = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
# A = np.array(A)
# B = [[1, 2], [1, 3]]
# B = np.array(B)
print("Array A:\n",A)
print("Array B:\n",B)

matching = []

for i in A:
    ok = True
    for j in B:
        if not all(e in i for e in j):
            ok = False
            break
    matching.append(ok)

matching = np.array(matching)
matching_rows = A[matching]

print("\nLines in A, all the elements there are in B:\n", matching_rows)


Array A:
 [[ -4   5   7]
 [-10  -4   1]
 [  9   3   6]
 [  1  -3  -6]
 [  9  -7   7]
 [ -5   1  -8]
 [  5  -9   4]
 [  8   4   8]]
Array B:
 [[-1 -7]
 [-7 -6]]

Lines in A, all the elements there are in B:
 []


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [370]:
a = np.random.randint(2, 3, size=(10,3))
print(a)
comp_condition = (a == a[:,[0]])
equal = comp_condition.all(axis=1)
matching_rows = a[~equal]
print("Answer:\n", matching_rows)


[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
Answer:
 []


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [371]:
a = np.random.randint(1, 3, size=(10,3))
print(a)
a = np.unique(a, axis=0)
print(a)

[[1 2 1]
 [2 2 2]
 [1 2 2]
 [2 2 2]
 [1 1 1]
 [2 2 2]
 [1 2 2]
 [2 2 2]
 [1 2 2]
 [1 2 2]]
[[1 1 1]
 [1 2 1]
 [1 2 2]
 [2 2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [372]:
x = [[1,0,1], [2,0,2], [3,0,3], [4,4,4]]
i=0
p=1
rows = len(x)
cols = len(x[0])
n = min(rows, cols)
while (i<n):
    if(x[i][i]!=0):
        p = p * x[i][i]
    i = i + 1

print(p)

y = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
d = np.diag(y)
filteredD = d[d!=0]
p = np.prod(filteredD)

print(p)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [373]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(sorted(x)==sorted(y))

ux, cx = np.unique(x, return_counts=True)
uy, cy = np.unique(y, return_counts=True)
print(np.array_equal(ux, ux) and np.array_equal(uy, uy))


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [374]:
x = np.array([0, 5, 0, -1, 4, 0])
max = None
i = 0
length = len(x)-1
while (i<length):
    if(x[i]==0):
        if (max == None):
            max = x[i+1]
        if (max < x[i+1]):
            max=x[i+1]
    i=i+1

if(max!=None):
    while i < length:
        if(x[i] == 0):
            if (x[i+1]>max):
                max = x[i+1]
        i = i+1
    print('Max element after zero:', max)
else:
    print('No element after zero or there is no zero. Max element:', max)

zero_index = np.where(x == 0)[0]
zero_index = zero_index[zero_index<len(x)-1]
after_zero = x[zero_index+1]
if after_zero.size==0:
    print('No element after zero or there is no zero. Max element:', max)
else:
    max = after_zero.max()
    print('Max element after zero:', max)

Max element after zero: 5
Max element after zero: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [375]:
x = np.array([2, 2, 2, 3, 3, 3, 2, 2, 5])
y = [2, 2, 2, 3, 3, 3, 2, 2, 5]

unique = []
uniquec = []
counts = 0
current = y[0]
for i in y:
    if (i == current):
        counts+=1
    else:
        unique.append(current)
        uniquec.append(counts)
        current = i
        counts = 1

unique.append(current)
uniquec.append(counts)

print('Elements:', unique, 'Counts:', uniquec)

idx = np.flatnonzero(np.diff(x)) + 1
unique = x[np.r_[0, idx]]
uniquec = np.diff(np.r_[0, idx, len(x)])
print('Elements:', unique, 'Counts:', uniquec)

Elements: [2, 3, 2, 5] Counts: [3, 3, 2, 1]
Elements: [2 3 2 5] Counts: [3 3 2 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [376]:
import math

X = np.array([[0,0],[1,1]])
Y = np.array([[1,0],[2,2]])
# X = np.random.rand(1000, 10)
# Y = np.random.rand(1000, 10)

def distance_matrix_python_comp(X, Y):
    return [[math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b))) for b in Y] for a in X]

print(distance_matrix_python_comp(X, Y))

D_numpy = np.sqrt(((X[:, None, :] - Y[None, :, :]) ** 2).sum(axis=2))
print(D_numpy)

from scipy.spatial.distance import cdist

D_scipy = cdist(X, Y, metric='euclidean')
print(D_scipy)

import timeit
t1 = timeit.timeit(lambda: distance_matrix_python_comp(X.tolist(), Y.tolist()), number=1)
t2 = timeit.timeit(lambda: np.sqrt(((X[:, None, :] - Y[None, :, :]) ** 2).sum(axis=2)), number=1)
t3 = timeit.timeit(lambda: cdist(X, Y, metric='euclidean'), number=1)

print(f"Python: {t1*1000:.4f} ms")
print(f"NumPy: {t2*1000:.4f} ms")
print(f"SciPy cdist: {t3*1000:.4f} ms")


[[1.0, 2.8284271247461903], [1.0, 1.4142135623730951]]
[[1.         2.82842712]
 [1.         1.41421356]]
[[1.         2.82842712]
 [1.         1.41421356]]
Python: 0.0220 ms
NumPy: 0.0449 ms
SciPy cdist: 0.0290 ms


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [377]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [378]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [379]:
average_calories = round(np.average(calorie_stats))
print(f'Average amount of calories is more than in CrunchieMunchies on {average_calories-60} calories')

Average amount of calories is more than in CrunchieMunchies on 47 calories


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [380]:
calorie_stats_sorted = np.sort(calorie_stats)
print('Sorted calorie stats:', calorie_stats_sorted)

Sorted calorie stats: [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [381]:
median_calorties = np.median(calorie_stats)
print('Median calories:', median_calorties, 'Average calories:', average_calories)

Median calories: 110.0 Average calories: 107


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [382]:
percentile50 = np.percentile(calorie_stats, 50)
percentile25 = np.percentile(calorie_stats, 25)
percentile10 = np.percentile(calorie_stats, 10)
percentile5 = np.percentile(calorie_stats, 5)
percentile4 = np.percentile(calorie_stats, 4)
percentile3 = np.percentile(calorie_stats, 3)

print(f'50% percentile: {percentile50:.2f} ')
print(f'25% percentile: {percentile25:.2f} ')
print(f'10% percentile: {percentile10:.2f} ')
print(f'5% percentile: {percentile5:.2f} ')
print(f'4% percentile: {percentile4:.2f} ')
print(f'3% percentile: {percentile3:.2f} ')

i = 100

while i>0:
    if(np.percentile(calorie_stats, i)>60):
        nth_percentile = i
    i=i-1

print(f'CrunchieMunchies has less calories than: {100-nth_percentile} % of other cereals')

50% percentile: 110.00 
25% percentile: 100.00 
10% percentile: 90.00 
5% percentile: 70.00 
4% percentile: 70.00 
3% percentile: 55.60 
CrunchieMunchies has less calories than: 96 % of other cereals


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [383]:
amount_more = np.sum(calorie_stats>60)
all_amount = calorie_stats.shape[0]
more_calories = round(100*amount_more/all_amount, 2)
print(f'{more_calories}% of cereals have more than 60 calories')

96.1% of cereals have more than 60 calories


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [384]:
calorie_std = np.std(calorie_stats)
print('Standart deviation is:', round(calorie_std, 1), 'calories.\nThis meaning we should consider as moderate, because it is between 10-30% of average meaning. So we can generalize that dataset is suitable and values are significant.')

Standart deviation is: 19.4 calories.
This meaning we should consider as moderate, because it is between 10-30% of average meaning. So we can generalize that dataset is suitable and values are significant.


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [385]:
print('This way data about calories may be used as a unique selling proposition and also as an element of marketing and advertising campaign.')

This way data about calories may be used as a unique selling proposition and also as an element of marketing and advertising campaign.
